### ISSUE TITLE
Method of transferring app to server causes error in grpc_csharp_ext.x64.dll

### ISSUE THREAD

**Issue by steveoh** [manigandham/serilog-sinks-googlecloudlogging#22]
### Describe the bug

I am using npm, grunt, and dotnet to built and deploy a `dotnet new react` project on osx. When this pipeline runs, the project fails to start with a 502.5 error. If I go to the server and execute `dotnet app.dll` I get a strange error.

#### Stack trace

```shell
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.IOException: Error loading native library "C:\...\runtimes/win/native\grpc_csharp_ext.x64.dll".
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSink..ctor(GoogleCloudLoggingSinkOptions sinkOptions, MessageTemplateTextFormatter messageTemplateTextFormatter, Int32 batchSizeLimit, TimeSpan period)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, GoogleCloudLoggingSinkOptions sinkOptions, Nullable`1 batchSizeLimit, Nullable`1 period, String outputTemplate)
   at Serilog.Sinks.GoogleCloudLogging.GoogleCloudLoggingSinkExtensions.GoogleCloudLogging(LoggerSinkConfiguration loggerConfiguration, String projectId, String resourceType, String logName, Dictionary`2 labels, Dictionary`2 resourceLabels, Boolean useSourceContextAsLogName, Boolean useJsonOutput, String googleCredentialJson, String serviceName, String serviceVersion, Nullable`1 batchSizeLimit, Nullable`1 period, String outputTemplate)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Serilog.Settings.Configuration.ConfigurationReader.CallConfigurationMethods(ILookup`2 methods, IList`1 configurationMethods, Object receiver)
   at Serilog.Settings.Configuration.ConfigurationReader.Configure(LoggerConfiguration loggerConfiguration)
   at Serilog.Configuration.LoggerSettingsConfiguration.Settings(ILoggerSettings settings)
   at app.Program.Main(String[] args) in /Users/.../src/Program.cs:line 17
```

#### Somewhat related issues?

https://github.com/grpc/grpc/issues/11914
https://github.com/grpc/grpc/issues/12570

### Reproduce

Currently, I use npm scripts to run 

1. `dotnet publish -c Release`
1. `npm build` to build the react app 
1. grunt-contrib-compress to compress the `bin/release/netcoreapp2.2/publish/` folder
1. grunt-ssh then pushes an `app_offline.htm` the file to a windows 2016 server running openssh to stop the app. 
1. grunt-ssh sends the publish zip and unzips the project overwriting the old app.

The strangest part is if I RDP into the server and copy the files from the same publish folder the application starts as expected.

What could possibly be causing the above error in the compression, file transfer, and uncompression process?

I posted this to [aspnet core](https://github.com/aspnet/AspNetCore/issues/12101) but it was closed and identified as a problem here.

from david fowler

> This isn't related to ASP.NET Core or GRPC. It looks like an issue with the serilog GCP logging sink which happens to be using the native interop C# grpc implementation. The issue should be moved to this repository manigandham/serilog-sinks-googlecloudlogging

**Comment by manigandham** [comment]
@steveoh 

This library uses the official [Google Cloud SDK libraries for .NET](https://github.com/googleapis/google-cloud-dotnet) and most of these APIs communicate over [GRPC](https://grpc.io/). 

That RPC/communication is handled by a native library which means it has to be compatible with the underlying OS platform. The first line in your stack trace shows that it's trying to load the 64-bit Windows library but you're running it on Mac OS so that's why its failing. I'm not sure why its not picking the correct native library automatically but it's not part of this logging sink.

Is your `dotnet publish` command just that or are you building it for a specific OS platform? Can you paste the entire build script that's running?

**Comment by steveoh** [comment]
@manigandham I am publishing/building from osx to windows.

`ASPNETCORE_ENVIRONMENT=Staging dotnet publish ../app.csproj -c Release`

https://github.com/agrc/parole-and-probation/blob/master/src/ClientApp/package.json#L38-L40 is the build script.

**Comment by manigandham** [comment]
Just saw that, can you run the build and check in the publish directory for a folder called `runtimes`? Is there a `osx` folder in there?

**Comment by steveoh** [comment]
The dll is present.

![image](https://user-images.githubusercontent.com/325813/61232349-55e35d00-a6eb-11e9-8406-b1d77c092cd6.png)

**Comment by manigandham** [comment]
Ah ok, in that case it's probably on the server side. I'm assuming this is running in IIS then if you're using `app_offline.htm`? The files are probably locked by IIS when the app is starting.

**Comment by steveoh** [comment]
Interesting idea. Is that a common issue with known solutions?

**Comment by manigandham** [comment]
Yes [its common](https://www.google.com/search?q=iis+dll+files+locked). The official solution for deploying to IIS is to use WebDeploy but that doesn't run on OSX. You might have to use some scripting and stop the entire app pool or server before overwriting the files, then restart after.

**Comment by steveoh** [comment]
I was under the impressions that app_offline stops the app pool.

**Comment by steveoh** [comment]
I do not believe this is an issue, the app doesn't start so no lock is created by iis. And if I copy the **same** files via RDP, the issue is not present.

**Comment by manigandham** [comment]
Did you get this figured out?

**Comment by steveoh** [comment]
unfortunately nope.

**Comment by manigandham** [comment]
Closing now since this isn't related to this library.

**Comment by steveoh** [comment]
I'm still running into issues with this... 

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: Error loading native library "C:\app\runtimes/win/native\grpc_csharp_ext.x64.dll". 
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
```

this stack trace has the path all fouled up

**Comment by manigandham** [comment]
I'm not sure how to help here since this is a deployment problem and not related to this library. Here are some ideas you can try:

- Add explicit references to the GRPC nuget libraries.
- Skip the compress step and just copy the files directly to avoid corrupting them.
- Use WebDeploy to push directly to IIS if you're deploying from Windows instead of the grunt setup.

**Comment by steveoh** [comment]
The issue was with the encoding on the sftp transfer I think

**Comment by manigandham** [comment]
You might also have problems if the build environment (linux/macos) is different than the running environment (windows).

**Comment by steveoh** [comment]
I've tried this now with windows and web deploy and I get the same errors.

**Comment by manigandham** [comment]
Hey, I can't really help with this because it's not related to this library. You'll need to check with the GRPC projects to see what's happening. Since .NET 5.0 has been released, I'd try upgrading to that first. Also this logging library is MIT licensed and only has a few files that you can just copy/paste into your project and reduce a dependency.

**Comment by steveoh** [comment]
So the root issue is that the grpc dll only had read write permissions and it needs execute permissions.

**Comment by manigandham** [comment]
awesome, glad you got it figured out! thanks for documenting the fix too
